apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ns-user-service
  labels:
    app: user-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: user-service