// Code generated by mockery v2.42.3. DO NOT EDIT.

package get_review_by_id_contract

import (
	context "context"

	entities "github.com/jfelipearaujo-healthmed/user-service/internal/core/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, userID, reviewID
func (_m *MockUseCase) Execute(ctx context.Context, userID uint, reviewID uint) (*entities.Review, error) {
	ret := _m.Called(ctx, userID, reviewID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Review
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*entities.Review, error)); ok {
		return rf(ctx, userID, reviewID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *entities.Review); ok {
		r0 = rf(ctx, userID, reviewID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, userID, reviewID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
