// Code generated by mockery v2.42.3. DO NOT EDIT.

package update_user

import (
	context "context"

	entities "github.com/jfelipearaujo-healthmed/user-service/internal/core/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, userID, newUser
func (_m *MockUseCase) Execute(ctx context.Context, userID uint, newUser *entities.User) error {
	ret := _m.Called(ctx, userID, newUser)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *entities.User) error); ok {
		r0 = rf(ctx, userID, newUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
