@startuml create_user

title Criação de Usuário

actor "User" as user
participant "User Service" as user_service
participant "Database" as database

note over user
O usuário pode ser um **médico**
ou um **paciente**.
end note

user -> user_service: POST /users

note over user_service
Esta rota não requer autenticação
end note

activate user_service
user_service -> user_service: Valida os dados
user_service -> database: Cria o usuário
database --> user_service: Criado
user_service --> user: 201 Criado
deactivate user_service

@enduml