@startuml get_user

title Getting an User Flow

actor "User" as user
participant "User Service" as user_service
participant "Database" as database

note over user
In this example, the user could be
a **doctor** or a **patient**.
end note

user -> user_service: GET /users/me\n(Bearer JWT)
activate user_service
user_service -> user_service: Get user based on JWT
user_service -> database: Get user
database --> user_service: Found
user_service --> user: 200 OK
deactivate user_service

@enduml