@startuml login

title Login de Usuário

actor "User" as user
participant "User Service" as user_service
participant "Database" as database

note over user
O usuário pode ser um **médico**
ou um **paciente**.
end note

user -> user_service: POST /users/login

note over user_service
O serviço do usuário validará as
credenciais de acordo com o método de login
escolhido pelo usuário.

Se o usuário for um **médico**, o
serviço validará o
**ID médico** e a **senha**.

Se o usuário for um **paciente**, o
serviço validará o
**e-mail** ou **ID do documento (CPF)**
e a **senha**.
end note

activate user_service
user_service -> user_service: Valida os dados
user_service -> database: Verifica se o usuário existe
database --> user_service: Usuário encontrado
user_service -> user_service: Cria um token de acesso
user_service --> user: 200 OK
deactivate user_service

@enduml