@startuml search_doctors

title Pesquisa de Médicos

actor "User" as user
participant "User Service" as user_service
participant "Database" as database

note over user
O usuário pode ser um **paciente**.
end note

user -> user_service: GET /users/doctors\n(Bearer JWT)
activate user_service
user_service -> database: Busca os médicos

note over database
Esta consulta pode ser filtrada por
especialidade, ID médica, rua,
estado, CEP, etc.
end note

database --> user_service: Encontrados
user_service --> user: 200 OK
deactivate user_service

@enduml