name: destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Attach to EKS cluster
        run: aws eks update-kubeconfig --region us-east-1 --name healthmed

      - name: Destroy from EKS
        run: make k8s-destroy id=${{ secrets.AWS_ACCOUNT_ID }}