name: provisioning

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Build
        run: make build
  
  test:
    needs: 
      - build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Test
        run: make test

  image:
    needs: 
      - test
    name: Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t jsfelipearaujo/user-service:latest -t jsfelipearaujo/user-service:v${{ github.run_number }} .

      - name: Push image
        run: |
          docker push jsfelipearaujo/user-service:latest
          docker push jsfelipearaujo/user-service:v${{ github.run_number }}

  deploy:
    needs: 
      - image
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Attach to EKS cluster
        run: aws eks update-kubeconfig --region us-east-1 --name healthmed

      - name: Deploy to EKS
        run: make k8s-deploy id=${{ secrets.AWS_ACCOUNT_ID }}

      - name: Update deployment
        run: kubectl set image deployments/user-service user-service=jsfelipearaujo/user-service:v${{ github.run_number }} -n ns-user-service

      - name: Wait for deployment
        run: kubectl rollout status deployments/user-service -n ns-user-service